export const colors = {
  background: '#f8fbff',
  surface: '#ffffff',
  surfaceMuted: '#f1f6ff',
  surfaceSoft: '#fbfdff',
  hero: '#edf4ff',
  border: '#dfe8f5',
  borderStrong: '#cfdcf0',
  text: '#1f2d3d',
  textSecondary: '#607086',
  textMuted: '#8795a8',
  primary: '#3d7df6',
  primarySoft: '#e9f1ff',
  secondary: '#6aa8ff',
  secondarySoft: '#f1f6ff',
  accent: '#8ab7ff',
  warning: '#f2a65a',
  warningSoft: '#fff0dd',
  success: '#2f9e6d',
  successSoft: '#e5f7ef',
  danger: '#d45d63',
  dangerSoft: '#fff1f2',
  route: '#4d8dff',
};
